renderer:
  debugGrid: false
  memberWidth: 220
  memberHeight: 200
  imageSize: 110
  lineVerticalSpace: 80
  dateFormat: yyyy.MM.dd

logging:
  level:
    hu.skzs.familytree: INFO
    root: INFO